[package]
name = "world_state"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
color-eyre = { workspace = true }
context_attribute = { workspace = true }
coordinate_systems = { workspace = true }
filtering = { workspace = true }
framework = { workspace = true }
hardware = { workspace = true }
linear_algebra = { workspace = true }
serde = { workspace = true }
spl_network_messages = { workspace = true }
tokio = { workspace = true }
types = { workspace = true }
